# Generated by Django 5.1.6 on 2025-02-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
