# Generated by Django 5.1.6 on 2025-02-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_created_date_alter_todo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(),
        ),
    ]
